name: Publicar Documentação na Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      # 1. Faz checkout do repositório principal
      - name: Checkout do Repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Clona o repositório da Wiki
      - name: Clonar Wiki
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

      # 3. Copia os arquivos de documentação para a Wiki
      - name: Copiar Documentação
        run: |
          mkdir -p wiki
          cp -r docs/* wiki/

      # 4. Commit e push na Wiki
      - name: Publicar na Wiki
        run: |
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Atualização automática da Wiki [skip ci]" || echo "Nada para atualizar"
          git push origin main
